- name: install and configure The Node Application
  hosts: API_SERVER

  NODE_VERSION: v18.3.0



- name: Basic usage
  debug:
    msg: |
        "'{{ lookup('env', 'HOME') }}' is the HOME environment variable."
        "'{{ lookup('env', 'REPO_NAME') }}' is the Reposotiory name."



      tasks:
          - name: Copying file with playbook
            become: true
            copy:
                src: /home/runner/work/REPO_NAME
                dest: /home/dev
                owner: dev
                mode: 0644
          - name: Installing Node dependencies
            ansible.builtin.command: /home/API_SERVESES/.nvm/versions/node/{{NODE_VERSION}}/bin/npm i
            environment:
                PATH: "{{ ansible_env.PATH }}:/home/API_SERVESES/.nvm/versions/node/{{NODE_VERSION}}/bin"
            args:
                chdir: /home/API_SERVESES/{{REPO_NAME}}
