- name: install and configure The Node Application
  hosts: API

  vars:
      - NODE_VERSION: v18.3.0
      - REPO_NAME: ainfras
      

  tasks:
  
#       - name: Stop the API Service
#         become_user: dep
#         ansible.builtin.command: "pm2 stop all"
#         args:
#             chdir: /home/dep/owk-api-gateway

      - name: pm2 stop
        become: yes
        ansible.builtin.command: "pm2 stop all"
        environment:
          PATH: "{{ ansible_env.PATH }}"

            
      - name: Clone The Repo
        ansible.builtin.git:
           force: yes
           repo: git@github.com:noatheo/ainfras.git
           dest: /home/dep/{{REPO_NAME}}
               
      - name: Adding Environment Variable
        become_user: dep
        ansible.builtin.shell: bash envadd.sh
        args:
          chdir: /home/dep/{{REPO_NAME}}
        
      - name: Reprocess Environment Variables.
        become_user: dep
        ansible.builtin.shell: |
          source ~/.bashrc
          source ~/.profile
        args:
            executable: /bin/bash
     
      - name: Installing Node Dependencies
        ansible.builtin.command: /home/dep/.nvm/versions/node/{{NODE_VERSION}}/bin/npm i
        environment:
            PATH: "{{ ansible_env.PATH }}:/home/dep/.nvm/versions/node/{{NODE_VERSION}}/bin"
        args:
            chdir: /home/dep/owk-api-gateway
       
      - name: Run the API Service
        ansible.builtin.command: "/home/dep/.nvm/versions/node/{{NODE_VERSION}}/bin/pm2 start npm -- start -i max"
        environment:
            PATH: "{{ ansible_env.PATH }}:/home/dep/.nvm/versions/node/{{NODE_VERSION}}/bin"
        args:
            chdir: /home/dep/owk-api-gateway
            
            
     
      
      
      
