- name: install and configure The Node Application
  hosts: API

  vars:
      - NODE_VERSION: v18.3.0
      - REPO_NAME: ainfras

  tasks:
      - name: clone The repo
        ansible.builtin.git:
           force: yes
           repo: git@github.com:noatheo/ainfras.git
           dest: /home/dep
            
            
      - name: Installing Node dependencies
        ansible.builtin.command: /home/dep/.nvm/versions/node/{{NODE_VERSION}}/bin/npm i
        environment:
            PATH: "{{ ansible_env.PATH }}:/home/dep/.nvm/versions/node/{{NODE_VERSION}}/bin"
        args:
            chdir: /home/dep/{{REPO_NAME}}
            
      
