- name: Install and configure The Node Application
  hosts: API
  become: yes

  vars:
      - NODE_VERSION: v18.3.0
      - REPO_NAME: ainfras
      - USER: dep
      

  tasks:
            
      - name: delete all the API Services
        become_user: '{{USER}}'
        ansible.builtin.shell: bash -ilc "pm2 delete all"
        register: ret
        failed_when: ("[PM2][ERROR]" in ret.stdout)
        args:
            chdir: '~/{{REPO_NAME}}'
            
      - name: Cloning The Repo
        become_user: '{{USER}}'
        ansible.builtin.git:
          repo: 'git@github.com:noatheo/ainfras.git'
          dest: /home/dep/ainfras
          version: main
          force: yes
       
      
          
      - name: Adding Environment Variable
        become_user: '{{USER}}'
        ansible.builtin.shell: bash envadd.sh
        args:
          chdir: "~/{{REPO_NAME}}/Scripts"
        
      - name: Adding Environment Variable
        become_user: '{{USER}}'
        ansible.builtin.shell: |
          bash -ilc "source .bashrc"
          bash -ilc "source .profile"
        args:
          chdir: "/home/{{USER}}"
               
      - name: 'Give Access to the NODE to open port 80'
        ansible.builtin.shell: |
           setcap 'cap_net_bind_service=+ep' /home/'{{USER}}'/.nvm/versions/node/'{{NODE_VERSION}}'/bin/node
        args:
          chdir: '~'        
               
      - name: Installing Node Dependencies
        become_user: '{{USER}}'
        ansible.builtin.shell: bash -ilc "npm ci"
        args:
          chdir: '~/owk-api-gateway'
    
       
      - name: Run the API Service
        become_user: '{{USER}}'
        ansible.builtin.shell: |
          bash -ilc "pm2 start npm -- start -i max"
        args:
            chdir: '~/owk-api-gateway'
            
     
      
