name: Deployning API_SERVESES 

on:
    push:
        branch: 
            - master


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo 
          uses: actions/checkout@v2  
        - name: Install Ansible 
          run : |
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            python get-pip.py --user
            python -m pip install --user ansible
        - name: Run ansible playbook
          run: |
            echo ${{secrets.SSH_PRIVATE_KEY}} >> key.txt
            ansible-playbook deployment.staging.yaml -i inventroy.txt --private-key ./key.txt
        
