name: Deployning API_SERVESES 

on:
    push:
        branch: 
            - master


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo 
          uses: actions/checkout@v2  
        - name: finding ssh
          run: ssh-add - <<< "${{secrets.SSH_PRIVATE_KEY}}"
        - name: connecting 
          run: |
            ssh 35.221.63.71
            echo "hello"
          

        
