name: Deployning API_SERVESES 

on:
    push:
        branches: 
            - main
concurrency:
    group: staging-pipeline-${{ github.head_ref }}
    cancel-in-progress: true



jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo 
          uses: actions/checkout@v2  
        - name: finding ssh
          run: |
            echo "${{secrets.SSH_PRIVATE_KEY}}" >> keyfile
            chmod 400 /home/runner/work/ainfras/ainfras/keyfile
            echo "${{secrets.INVENTORY}}" >> inventory

        - name: connecting 
          run: |
            ssh -tti /home/runner/work/ainfras/ainfras/keyfile -o StrictHostKeyChecking=no -T dep@34.86.105.222

        - name: Install Ansible 
          run : |
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            python get-pip.py --user
            python -m pip install --user ansible
 
        - name: applying ansible
          run: ansible-playbook ${{secrets.WORKSPACE}}/Scripts/deployment.staging.yaml -i inventory
          
        - name: Deleting secret files
          run: rm -f keyfile inventory
            
          

        
