name: Deployning API_SERVESES 

on:
    push:
        branch: 
            - master
concurrency:
    group: staging-pipeline-${{ github.head_ref }}
    cancel-in-progress: true

env:
    HELLO: "hdjdksahjhsakdjhsakjdhakj" 

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo 
          uses: actions/checkout@v2  
        - name: finding ssh
          run: |
            echo "${{secrets.SSH_PRIVATE_KEY}}" >> sec
            chmod 400 /home/runner/work/ainfras/ainfras/sec
            ls -a
            readlink -f sec
        - name: connecting 
          run: |
            ssh -tti /home/runner/work/ainfras/ainfras/sec -o StrictHostKeyChecking=no -T dep@35.221.63.71
#            ssh -tti /home/runner/work/ainfras/ainfras/sec -o StrictHostKeyChecking=no dep@35.221.63.71
#            ls >> somewdkijslkfjdsk.txt
 #           exit
        - name: Install Ansible 
          run : |
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            python get-pip.py --user
            python -m pip install --user ansible
 
        - name: applying ansible
          run: ansible-playbook deployment.staging.yaml -i inventroy
            
          

        
