name: Deployning API_SERVESES 

on:
    push:
        branch: 
            - master


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo 
          uses: actions/checkout@v2  
        - name: finding ssh
          run: |
            echo "${{secrets.SSH_PRIVATE_KEY}}" >> sec
            chmod 400 /home/runner/work/ainfras/ainfras/sec
            ls -a
            readlink -f sec
        - name: connecting 
          run: |
            ssh -tti /home/runner/work/ainfras/ainfras/sec -o StrictHostKeyChecking=no dep@35.221.63.71
            echo "hello" > somewdkijslkfjdsk.txt
            exit
          

        
