name: Deployning API_SERVESES 

on:
    push:
        branch: 
            - master


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo 
          uses: actions/checkout@v2  
        - name: finding ssh
          run: ssh

        
